
name = "STFATE"
version = "0.1.0"
license = "MIT"
maintainer = "jonathanm@vt.edu"
author = "WaveHello"
copyright = "Copyright 2020 Jonathan Moore"
description = "Implementation of the STFATE model for simulating dredge material transport and fate in aquatic environments."
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
# external-modules = ["stdlib"]

[dependencies]

# stdlib = { git = "https://github.com/fortran-lang/stdlib", branch = "stdlib-fpm" }
stdlib = {path = "../../stdlib"}
# fortplot = { git = "https://github.com/krystophny/fortplot" }

[dev-dependencies]
# fortplot = { git = "https://github.com/krystophny/fortplot/" }
test-drive = {git = "https://github.com/fortran-lang/test-drive.git"}

[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
